export const usuarios = {
  usuarios: [
    {
      id: 1,
      nome: "João Silva",
      email: "joao@example.com",
      data_de_criacao: "15-05-2022",
      cidade: "São Paulo",
      permissoes: {
        leitura: true,
        escrita: true,
        exclusao: false,
      },
    },
    {
      id: 2,
      nome: "Maria Santos",
      email: "maria@example.com",
      data_de_criacao: "30-11-2021",
      cidade: "Rio de Janeiro",
      permissoes: {
        leitura: true,
        escrita: false,
        exclusao: false,
      },
    },
    {
      id: 3,
      nome: "Carlos Oliveira",
      email: "carlos@example.com",
      data_de_criacao: "10-02-2023",
      cidade: "Belo Horizonte",
      permissoes: {
        leitura: true,
        escrita: true,
        exclusao: true,
      },
    },
    {
      id: 4,
      nome: "Ana Rodrigues",
      email: "ana@example.com",
      data_de_criacao: "05-08-2022",
      cidade: "Salvador",
      permissoes: {
        leitura: true,
        escrita: true,
        exclusao: false,
      },
    },
    {
      id: 5,
      nome: "Lucas Pereira",
      email: "lucas@example.com",
      data_de_criacao: "20-03-2021",
      cidade: "Brasília",
      permissoes: {
        leitura: true,
        escrita: false,
        exclusao: false,
      },
    },
    {
      id: 6,
      nome: "Julia Souza",
      email: "julia@example.com",
      data_de_criacao: "12-09-2023",
      cidade: "Recife",
      permissoes: {
        leitura: true,
        escrita: true,
        exclusao: true,
      },
    },
    {
      id: 7,
      nome: "Pedro Costa",
      email: "pedro@example.com",
      data_de_criacao: "25-01-2022",
      cidade: "Fortaleza",
      permissoes: {
        leitura: true,
        escrita: true,
        exclusao: false,
      },
    },
    {
      id: 8,
      nome: "Larissa Ferreira",
      email: "larissa@example.com",
      data_de_criacao: "08-06-2022",
      cidade: "Porto Alegre",
      permissoes: {
        leitura: true,
        escrita: false,
        exclusao: true,
      },
    },
    {
      id: 9,
      nome: "Rafaela Gonçalves",
      email: "rafaela@example.com",
      data_de_criacao: "16-12-2021",
      cidade: "Curitiba",
      permissoes: {
        leitura: true,
        escrita: true,
        exclusao: true,
      },
    },
    {
      id: 10,
      nome: "Gustavo Lima",
      email: "gustavo@example.com",
      data_de_criacao: "02-04-2023",
      cidade: "Manaus",
      permissoes: {
        leitura: true,
        escrita: false,
        exclusao: false,
      },
    },
    {
      id: 11,
      nome: "Fernanda Almeida",
      email: "fernanda@example.com",
      data_de_criacao: "19-07-2022",
      cidade: "Belém",
      permissoes: {
        leitura: true,
        escrita: true,
        exclusao: false,
      },
    },
    {
      id: 12,
      nome: "Daniel Santos",
      email: "daniel@example.com",
      data_de_criacao: "14-03-2021",
      cidade: "Natal",
      permissoes: {
        leitura: true,
        escrita: true,
        exclusao: false,
      },
    },
    {
      id: 13,
      nome: "Patrícia Barbosa",
      email: "patricia@example.com",
      data_de_criacao: "22-10-2022",
      cidade: "Maceió",
      permissoes: {
        leitura: true,
        escrita: false,
        exclusao: false,
      },
    },
    {
      id: 14,
      nome: "Marcelo Martins",
      email: "marcelo@example.com",
      data_de_criacao: "18-09-2021",
      cidade: "Porto Velho",
      permissoes: {
        leitura: true,
        escrita: true,
        exclusao: true,
      },
    },
    {
      id: 15,
      nome: "Sofia Sousa",
      email: "sofia@example.com",
      data_de_criacao: "03-05-2023",
      cidade: "João Pessoa",
      permissoes: {
        leitura: true,
        escrita: true,
        exclusao: false,
      },
    },
  ],
};
